# =============================================================================
# メンテナンス画面用 Lambda 関数 (ローカル代替) — ALB の Lambda ターゲットとして動作
# ---------------------------------------------------------------------------
# 配置場所:
#   compose/maintenance-lambda/app/maintenance.py → コンテナ内 /var/task/maintenance.py
#   compose の `command: ["maintenance.lambda_handler"]` がこの関数を呼ぶ。
#   このファイルはボリュームマウントされるため、内容を書き換えて
#   `docker compose restart maintenance-lambda` するだけで差し替え可能 (再ビルド不要)。
#
# 役割:
#   ALB (nginx) のリスナールールから呼ばれ、「メンテナンス画面 (HTML)」と
#   「メンテナンス用ステータスコード (既定 503)」を返す。
#   ALB の Lambda ターゲット統合と同じ応答形式:
#     { "statusCode": int, "statusDescription": str, "headers": {...},
#       "isBase64Encoded": bool, "body": str }
#   HTTP ↔ Lambda イベントの変換は alb-lambda-adapter が肩代わりする
#   (実 AWS では ALB 自身がこの変換を行う)。
#
# 差し替え時のポイント:
#   - ステータスコードは環境変数 MAINTENANCE_STATUS_CODE で変更可 (既定 503)。
#   - 画面 HTML はこのファイル内 MAINTENANCE_HTML を編集するか、
#     関数の戻り値 body をまるごと差し替える。
# =============================================================================
import os
import json
from datetime import datetime, timezone

# メンテナンス用ステータスコード (既定 503 Service Unavailable)
MAINTENANCE_STATUS_CODE = int(os.environ.get("MAINTENANCE_STATUS_CODE", "503"))
# クライアントへの再試行目安 (秒)。Retry-After ヘッダに載る。
RETRY_AFTER_SECONDS = os.environ.get("RETRY_AFTER_SECONDS", "300")
# 画面に表示するメンテナンス明けの目安 (任意)。空なら非表示。
MAINTENANCE_UNTIL = os.environ.get("MAINTENANCE_UNTIL", "")

_STATUS_TEXT = {
    200: "OK",
    503: "Service Unavailable",
    502: "Bad Gateway",
    418: "I'm a teapot",
}


def _render_html() -> str:
    """メンテナンス画面 HTML を生成する (差し替え対象)。"""
    until_block = (
        f'<p class="until">復旧予定: <strong>{MAINTENANCE_UNTIL}</strong></p>'
        if MAINTENANCE_UNTIL else ""
    )
    now = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
    return f"""<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ただいまメンテナンス中です</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ margin:0; font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
         display:flex; min-height:100vh; align-items:center; justify-content:center;
         background:#0f172a; color:#e2e8f0; }}
  .card {{ max-width:520px; padding:40px; text-align:center;
          background:#111827; border:1px solid #1f2937; border-radius:16px;
          box-shadow:0 10px 40px rgba(0,0,0,.4); }}
  .icon {{ font-size:56px; line-height:1; }}
  h1 {{ font-size:22px; margin:16px 0 8px; }}
  p {{ margin:8px 0; color:#94a3b8; line-height:1.7; }}
  .until strong {{ color:#e2e8f0; }}
  .meta {{ margin-top:24px; font-size:12px; color:#475569; }}
  .code {{ display:inline-block; margin-top:12px; padding:4px 10px; border-radius:999px;
          background:#1e293b; color:#fbbf24; font-size:12px; letter-spacing:.05em; }}
</style>
</head>
<body>
  <main class="card">
    <div class="icon">🛠️</div>
    <h1>ただいまメンテナンス中です</h1>
    <p>ご不便をおかけしております。<br>システムメンテナンスのため一時的にサービスを停止しています。</p>
    {until_block}
    <div class="code">HTTP {MAINTENANCE_STATUS_CODE}</div>
    <p class="meta">generated by maintenance-lambda / {now}</p>
  </main>
</body>
</html>"""


def lambda_handler(event, context):
    """
    ALB の Lambda ターゲットとして呼ばれる。
    event は ELB ターゲットグループ形式 (httpMethod / path / headers / body 等)。
    ここでは経路によらず常にメンテナンス応答を返す。
    """
    status = MAINTENANCE_STATUS_CODE
    body = _render_html()

    # ログ (docker logs maintenance-lambda で確認)
    print(json.dumps({
        "handler": "maintenance.lambda_handler",
        "path": event.get("path"),
        "method": event.get("httpMethod"),
        "statusCode": status,
    }, ensure_ascii=False))

    return {
        "statusCode": status,
        "statusDescription": f"{status} {_STATUS_TEXT.get(status, 'Maintenance')}",
        "isBase64Encoded": False,
        "headers": {
            "Content-Type": "text/html; charset=utf-8",
            "Retry-After": str(RETRY_AFTER_SECONDS),
            "Cache-Control": "no-store",
            "X-Maintenance": "true",
        },
        "body": body,
    }
